name: Automatically create release Pull request for merging develop into master.
on:
  push:
    branches:
      - 'master'
jobs:
  github_release_pr:
  
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Create a pull request for merging develop into master.
        run: gh pr create --title 'Automated PR after release' --body ' '
      - name: Slack Notification after PR is ready for review.
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: general
          SLACK_TITLE: 'NEW Pull Request is ready for Review!'
          SLACK_MESSAGE: 'A Pull Request needs your approval before merging to Master branch.'
          SLACK_BOT_TOKEN: xoxb-4048146805254-4054677642163-prh43w3ytBpyT0MvrZ8TVrP1
